site:
  appname: webConsole
  listen_addr: :2222
  runmode: prod
  static_dir: static/
  views_dir: views/
ssh:
  io_mode: 1  # the mode reading data from ssh server: channel mode (0) OR session mode (1)
jwt:
  jwt_secret: secret.console.hpc.gensh.me
  token_lifetime: 7200
  issuer: issuer.ssh.gensh.me
  query_token_key: _t