site:
  appname: ssh-web-console
  listen_addr: :2222
  runmode: prod
  deploy_host: console.hpc.gensh.me
  static_prefix: /
  hard_static_dir: ./dist/
  soft_static_dir: views/
ssh:
  #  io_mode: 1  # the mode reading data from ssh server: channel mode (0) OR session mode (1)
  buffer_checker_cycle_time: 60 # check buffer every { buffer_checker_cycle_time } ms. if buffer is not empty , then send buffered data back to client(browser/webSocket)
jwt:
  jwt_secret: secret.console.hpc.gensh.me
  token_lifetime: 7200
  issuer: issuer.ssh.gensh.me
  query_token_key: _t